<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2020/7/2
 * Time: 11:03
 */

namespace Extend\Sql\Pdo;


use Extend\Sql\Model;

class Pdo extends Model
{
    private $db;
    public function __construct()
    {

        $this->db = new Connet();

    
    }

    public function where($sql = '')
    {
        parent::where($sql); // TODO: Change the autogenerated stub
    }

    public function getAll($sql = '')
    {

//        $sth = $this->db->prepare($sql);
//        dd($sth);
//
//        $sth = $this->db->prepare($sql);
//        dd($sth);
//        $sth->execute();
//        return $sth->fetchAll();
    }
}